name: Build

on: 
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: linux, platform: linux-x64}
          - { os: macos-latest, target: darwin, platform: darwin-x64}
          - { os: macos-latest, target: darwin, platform: darwin-arm64}
          - { os: windows-latest, target: windows, platform: win32-x64}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/master
    - name: Build
      run: | 
            mkdir build
            cd build
            cmake ..
            cmake --build . --config Release
            ctest -V -C Release
            cmake --install . --config Release --prefix ${{ github.workspace }}/artifact/
          
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/
  release:
    name: Upload Release
    needs: [build]
    runs-on: [ubuntu-18.04]
    steps:
      - name: Download
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: zip win32-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: win32-x64.zip
          path: win32-x64
      - name: zip linux-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with: 
          filename: linux-x64.zip
          path: linux-x64
      - name: zip darwin-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: darwin-x64.zip
          path: darwin-x64
      - name: zip darwin-arm64
        uses: TheDoctor0/zip-release@v0.2.1
        with: 
          filename: darwin-arm64.zip
          path: darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: CodeFormat
          draft: true
          generate_release_notes: true
          files: |
            linux-x64.zip
            darwin-x64.zip
            darwin-arm64.zip
            win32-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}        
