name: CodeStyle

on:
  pull_request:
    branches: [master]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'LuaParser'
          - check: 'CodeFormatCode'
          - check: 'CodeFormatLib'
          - check: 'CodeFormat'
          - check: 'CodeFormatServer'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Clang Format Checker
      - uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '17'
          check-path: ${{ matrix.path['check'] }}
          fallback-style: 'file'